const products=[{
    id:1,
    image:"../images/product1.png",
    productname:"Spray",
    productprice:1050,
},
{
    id:2,
    image:"../images/product2.png",
    productname:"Insecticide Spray",
    productprice:2000,
},
{
    id:3,
    image:"../images/product3.png",
    productname:"Crop Cover",
    productprice:1000,
},
{
    id:4,
    image:"../images/product4.png",
    productname:"Herbicide",
    productprice:2050,
},
{
    id:5,
    image:"../images/product5.png",
    productname:"Weed Killer",
    productprice:1050,
},
{
    id:6,
    image:"../images/product6.png",
    productname:"Self Watering Spikes Plant",
    productprice:1050,
},
{
    id:7,
    image:"../images/product7.png",
    productname:"Klassic Watering Can",
    productprice:1050,
},
{
    id:8,
    image:"../images/product8.png",
    productname:"Kisan Kraft KK-PS5000 Pressure Spray Pump",
    productprice:1050,
},
{
    id:9,
    image:"../images/product9.png",
    productname:"Ugaoo Organic Vermicompost Fertilizer Manure",
    productprice:1050,
},
{
    id:10,
    image:"../images/product10.png",
    productname:"Waste Decomposer 10 Bottles",
    productprice:1050,
},
{
    id:11,
    image:"../images/product11.png",
    productname:"TrustBasket Neem Cake Powder Organic Fertilizer and Pest Repellent for Plants",
    productprice:1050,
},
{
    id:12,
    image:"../images/product12.png",
    productname:"Go Garden Growth Boost Liquid Fertilizer",
    productprice:1050,
},
{
    id:13,
    image:"../images/product13.png",
    productname:"Kisan Paddy Special Liquid Fertilizer",
    productprice:1050,
},
{
    id:14,
    image:"../images/product14.png",
    productname:"Organic Plant Bio Organic Potash",
    productprice:1050,
},
{
    id:15,
    image:"../images/product15.png",
    productname:"COIR GARDEN - Bone Meal Powder for Plants",
    productprice:1050,
},
{
    id:16,
    image:"../images/product16.png",
    productname:"Bloombuddy Growth Booster Fertilizer 1 KG Granules",
    productprice:1050,
},
{
    id:17,
    image:"../images/product17.png",
    productname:"Silicon Fertilizer (3 kg) for All Plant",
    productprice:1050,
},
{
    id:18,
    image:"../images/product18.png",
    productname:"SAPRETAILER Epsom Salt Magnesium Sulphate Fertilizer",
    productprice:1050,
},
]

export default products;
